version: '3.7'
services:
  web:
    build: ./flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./flask_app:/flask_app
    depends_on:
      - mongodb

  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"

  mongodb:
      image: mongo:4.2.3
      ports:
        - "27017:27017"

